FROM ubuntu:24.04

#instalacja python 3.10 na ubuntu
RUN apt-get update
RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y \
    python3.10=3.10.* \
    python3.10-venv=3.10.* \
    python3.10-dev=3.10.* \
    python3-pip \
    && apt clean && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

#instalacja java 8 i kotlin
RUN apt-get -y install openjdk-8-jdk kotlin wget unzip

#gradle + sqllite
RUN wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -P /tmp \
    && unzip /tmp/gradle-8.7-bin.zip -d /opt/ \
    && ln -s /opt/gradle-8.7/bin/gradle /usr/local/bin/gradle 
    
ENV PATH="/opt/gradle-8.7/bin:${PATH}"


WORKDIR /app
COPY . /app
RUN gradle build
CMD ["gradle", "run"]


